//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lupa_i_pupa.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user19Entities : DbContext
    {
        public user19Entities()
            : base("name=user19Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Division> Division { get; set; }
        public virtual DbSet<Group_visit> Group_visit { get; set; }
        public virtual DbSet<Number_group> Number_group { get; set; }
        public virtual DbSet<Personal_visit> Personal_visit { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
    }
}
