//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lupa_i_pupa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_visit
    {
        public int Id { get; set; }
        public string Fio { get; set; }
        public string Num_Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string Passport_seria { get; set; }
        public string Pasport_nomer { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Purpose { get; set; }
    }
}
