//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lupa_i_pupa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int id { get; set; }
        public string Fio { get; set; }
        public Nullable<int> idDivision { get; set; }
        public Nullable<int> idDepartment { get; set; }
        public Nullable<int> Code { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Division Division { get; set; }
    }
}
